#pragma once

#include "steam/steam_api.h"

#include <string>
#include <string_view>
#include <unordered_map>

constexpr size_t EResultMax = k_EResultTooManyPending + 1;

// clang-format off

//! A map for names of EResult members.
//! See more: https://partner.steamgames.com/doc/api/steam_api#EResult
inline std::unordered_map<EResult, std::string> EResult_names = {
    { k_EResultNone, "k_EResultNone" },
    { k_EResultOK, "k_EResultOK" },
    { k_EResultFail, "k_EResultFail" },
    { k_EResultNoConnection, "k_EResultNoConnection" },
    { k_EResultInvalidPassword, "k_EResultInvalidPassword" },
    { k_EResultLoggedInElsewhere, "k_EResultLoggedInElsewhere" },
    { k_EResultInvalidProtocolVer, "k_EResultInvalidProtocolVer" },
    { k_EResultInvalidParam, "k_EResultInvalidParam" },
    { k_EResultFileNotFound, "k_EResultFileNotFound" },
    { k_EResultBusy, "k_EResultBusy" },
    { k_EResultInvalidState, "k_EResultInvalidState" },
    { k_EResultInvalidName, "k_EResultInvalidName" },
    { k_EResultInvalidEmail, "k_EResultInvalidEmail" },
    { k_EResultDuplicateName, "k_EResultDuplicateName" },
    { k_EResultAccessDenied, "k_EResultAccessDenied" },
    { k_EResultTimeout, "k_EResultTimeout" },
    { k_EResultBanned, "k_EResultBanned" },
    { k_EResultAccountNotFound, "k_EResultAccountNotFound" },
    { k_EResultInvalidSteamID, "k_EResultInvalidSteamID" },
    { k_EResultServiceUnavailable, "k_EResultServiceUnavailable" },
    { k_EResultNotLoggedOn, "k_EResultNotLoggedOn" },
    { k_EResultPending, "k_EResultPending" },
    { k_EResultEncryptionFailure, "k_EResultEncryptionFailure" },
    { k_EResultInsufficientPrivilege, "k_EResultInsufficientPrivilege" },
    { k_EResultLimitExceeded, "k_EResultLimitExceeded" },
    { k_EResultRevoked, "k_EResultRevoked" },
    { k_EResultExpired, "k_EResultExpired" },
    { k_EResultAlreadyRedeemed, "k_EResultAlreadyRedeemed" },
    { k_EResultDuplicateRequest, "k_EResultDuplicateRequest" },
    { k_EResultAlreadyOwned, "k_EResultAlreadyOwned" },
    { k_EResultIPNotFound, "k_EResultIPNotFound" },
    { k_EResultPersistFailed, "k_EResultPersistFailed" },
    { k_EResultLockingFailed, "k_EResultLockingFailed" },
    { k_EResultLogonSessionReplaced, "k_EResultLogonSessionReplaced" },
    { k_EResultConnectFailed, "k_EResultConnectFailed" },
    { k_EResultHandshakeFailed, "k_EResultHandshakeFailed" },
    { k_EResultIOFailure, "k_EResultIOFailure" },
    { k_EResultRemoteDisconnect, "k_EResultRemoteDisconnect" },
    { k_EResultShoppingCartNotFound, "k_EResultShoppingCartNotFound" },
    { k_EResultBlocked, "k_EResultBlocked" },
    { k_EResultIgnored, "k_EResultIgnored" },
    { k_EResultNoMatch, "k_EResultNoMatch" },
    { k_EResultAccountDisabled, "k_EResultAccountDisabled" },
    { k_EResultServiceReadOnly, "k_EResultServiceReadOnly" },
    { k_EResultAccountNotFeatured, "k_EResultAccountNotFeatured" },
    { k_EResultAdministratorOK, "k_EResultAdministratorOK" },
    { k_EResultContentVersion, "k_EResultContentVersion" },
    { k_EResultTryAnotherCM, "k_EResultTryAnotherCM" },
    { k_EResultPasswordRequiredToKickSession, "k_EResultPasswordRequiredToKickSession" },
    { k_EResultAlreadyLoggedInElsewhere, "k_EResultAlreadyLoggedInElsewhere" },
    { k_EResultSuspended, "k_EResultSuspended" },
    { k_EResultCancelled, "k_EResultCancelled" },
    { k_EResultDataCorruption, "k_EResultDataCorruption" },
    { k_EResultDiskFull, "k_EResultDiskFull" },
    { k_EResultRemoteCallFailed, "k_EResultRemoteCallFailed" },
    { k_EResultPasswordUnset, "k_EResultPasswordUnset" },
    { k_EResultExternalAccountUnlinked, "k_EResultExternalAccountUnlinked" },
    { k_EResultPSNTicketInvalid, "k_EResultPSNTicketInvalid" },
    { k_EResultExternalAccountAlreadyLinked, "k_EResultExternalAccountAlreadyLinked" },
    { k_EResultRemoteFileConflict, "k_EResultRemoteFileConflict" },
    { k_EResultIllegalPassword, "k_EResultIllegalPassword" },
    { k_EResultSameAsPreviousValue, "k_EResultSameAsPreviousValue" },
    { k_EResultAccountLogonDenied, "k_EResultAccountLogonDenied" },
    { k_EResultCannotUseOldPassword, "k_EResultCannotUseOldPassword" },
    { k_EResultInvalidLoginAuthCode, "k_EResultInvalidLoginAuthCode" },
    { k_EResultAccountLogonDeniedNoMail, "k_EResultAccountLogonDeniedNoMail" },
    { k_EResultHardwareNotCapableOfIPT, "k_EResultHardwareNotCapableOfIPT" },
    { k_EResultIPTInitError, "k_EResultIPTInitError" },
    { k_EResultParentalControlRestricted, "k_EResultParentalControlRestricted" },
    { k_EResultFacebookQueryError, "k_EResultFacebookQueryError" },
    { k_EResultExpiredLoginAuthCode, "k_EResultExpiredLoginAuthCode" },
    { k_EResultIPLoginRestrictionFailed, "k_EResultIPLoginRestrictionFailed" },
    { k_EResultAccountLockedDown, "k_EResultAccountLockedDown" },
    { k_EResultAccountLogonDeniedVerifiedEmailRequired, "k_EResultAccountLogonDeniedVerifiedEmailRequired" },
    { k_EResultNoMatchingURL, "k_EResultNoMatchingURL" },
    { k_EResultBadResponse, "k_EResultBadResponse" },
    { k_EResultRequirePasswordReEntry, "k_EResultRequirePasswordReEntry" },
    { k_EResultValueOutOfRange, "k_EResultValueOutOfRange" },
    { k_EResultUnexpectedError, "k_EResultUnexpectedError" },
    { k_EResultDisabled, "k_EResultDisabled" },
    { k_EResultInvalidCEGSubmission, "k_EResultInvalidCEGSubmission" },
    { k_EResultRestrictedDevice, "k_EResultRestrictedDevice" },
    { k_EResultRegionLocked, "k_EResultRegionLocked" },
    { k_EResultRateLimitExceeded, "k_EResultRateLimitExceeded" },
    { k_EResultAccountLoginDeniedNeedTwoFactor, "k_EResultAccountLoginDeniedNeedTwoFactor" },
    { k_EResultItemDeleted, "k_EResultItemDeleted" },
    { k_EResultAccountLoginDeniedThrottle, "k_EResultAccountLoginDeniedThrottle" },
    { k_EResultTwoFactorCodeMismatch, "k_EResultTwoFactorCodeMismatch" },
    { k_EResultTwoFactorActivationCodeMismatch, "k_EResultTwoFactorActivationCodeMismatch" },
    { k_EResultAccountAssociatedToMultiplePartners, "k_EResultAccountAssociatedToMultiplePartners" },
    { k_EResultNotModified, "k_EResultNotModified" },
    { k_EResultNoMobileDevice, "k_EResultNoMobileDevice" },
    { k_EResultTimeNotSynced, "k_EResultTimeNotSynced" },
    { k_EResultSmsCodeFailed, "k_EResultSmsCodeFailed" },
    { k_EResultAccountLimitExceeded, "k_EResultAccountLimitExceeded" },
    { k_EResultAccountActivityLimitExceeded, "k_EResultAccountActivityLimitExceeded" },
    { k_EResultPhoneActivityLimitExceeded, "k_EResultPhoneActivityLimitExceeded" },
    { k_EResultRefundToWallet, "k_EResultRefundToWallet" },
    { k_EResultEmailSendFailure, "k_EResultEmailSendFailure" },
    { k_EResultNotSettled, "k_EResultNotSettled" },
    { k_EResultNeedCaptcha, "k_EResultNeedCaptcha" },
    { k_EResultGSLTDenied, "k_EResultGSLTDenied" },
    { k_EResultGSOwnerDenied, "k_EResultGSOwnerDenied" },
    { k_EResultInvalidItemType, "k_EResultInvalidItemType" },
    { k_EResultIPBanned, "k_EResultIPBanned" },
    { k_EResultGSLTExpired, "k_EResultGSLTExpired" },
    { k_EResultInsufficientFunds, "k_EResultInsufficientFunds" },
    { k_EResultTooManyPending, "k_EResultTooManyPending" },
};

//! A map for description of EResult members.
//! See more: https://partner.steamgames.com/doc/api/steam_api#EResult
inline std::unordered_map<EResult, std::string> EResult_descriptions = {
    { k_EResultNone, "Empty EResult value. You're not supposed to get this." },
    { k_EResultOK, "Success." },
    { k_EResultFail, "Generic failure." },
    { k_EResultNoConnection, "Your Steam client doesn't have a connection to the back-end." },
    { k_EResultInvalidPassword, "Password/ticket is invalid." },
    { k_EResultLoggedInElsewhere, "The user is logged in elsewhere." },
    { k_EResultInvalidProtocolVer, "Protocol version is incorrect." },
    { k_EResultInvalidParam, "A parameter is incorrect." },
    { k_EResultFileNotFound, "File was not found." },
    { k_EResultBusy, "Called method is busy - action not taken." },
    { k_EResultInvalidState, "Called object was in an invalid state." },
    { k_EResultInvalidName, "The name was invalid." },
    { k_EResultInvalidEmail, "The email was invalid." },
    { k_EResultDuplicateName, "The name is not unique." },
    { k_EResultAccessDenied, "Access is denied." },
    { k_EResultTimeout, "Operation timed out." },
    { k_EResultBanned, "The user is VAC2 banned." },
    { k_EResultAccountNotFound, "Account not found." },
    { k_EResultInvalidSteamID, "The Steam ID was invalid." },
    { k_EResultServiceUnavailable, "The requested service is currently unavailable." },
    { k_EResultNotLoggedOn, "The user is not logged on." },
    { k_EResultPending, "Request is pending, it may be in process or waiting on third party." },
    { k_EResultEncryptionFailure, "Encryption or Decryption failed." },
    { k_EResultInsufficientPrivilege, "Insufficient privilege." },
    { k_EResultLimitExceeded, "Too much of a good thing." },
    { k_EResultRevoked, "Access has been revoked (used for revoked guest passes.)" },
    { k_EResultExpired, "License/Guest pass the user is trying to access is expired." },
    { k_EResultAlreadyRedeemed, "Guest pass has already been redeemed by account, cannot be used again." },
    { k_EResultDuplicateRequest, "The request is a duplicate and the action has already occurred in the past, ignored this time." },
    { k_EResultAlreadyOwned, "All the games in this guest pass redemption request are already owned by the user." },
    { k_EResultIPNotFound, "IP address not found." },
    { k_EResultPersistFailed, "Failed to write change to the data store." },
    { k_EResultLockingFailed, "Failed to acquire access lock for this operation." },
    { k_EResultLogonSessionReplaced, "The logon session has been replaced." },
    { k_EResultConnectFailed, "Failed to connect." },
    { k_EResultHandshakeFailed, "The authentication handshake has failed." },
    { k_EResultIOFailure, "There has been a generic IO failure." },
    { k_EResultRemoteDisconnect, "The remote server has disconnected." },
    { k_EResultShoppingCartNotFound, "Failed to find the shopping cart requested." },
    { k_EResultBlocked, "A user blocked the action." },
    { k_EResultIgnored, "The target is ignoring sender." },
    { k_EResultNoMatch, "Nothing matching the request found." },
    { k_EResultAccountDisabled, "The account is disabled." },
    { k_EResultServiceReadOnly, "This service is not accepting content changes right now." },
    { k_EResultAccountNotFeatured, "Account doesn't have value, so this feature isn't available." },
    { k_EResultAdministratorOK, "Allowed to take this action, but only because requester is admin." },
    { k_EResultContentVersion, "A Version mismatch in content transmitted within the Steam protocol." },
    { k_EResultTryAnotherCM, "The current CM can't service the user making a request, user should try another." },
    { k_EResultPasswordRequiredToKickSession, "You are already logged in elsewhere, this cached credential login has failed." },
    { k_EResultAlreadyLoggedInElsewhere, "The user is logged in elsewhere. (Use k_EResultLoggedInElsewhere instead!)" },
    { k_EResultSuspended, "Long running operation has suspended/paused. (eg. content download.)" },
    { k_EResultCancelled, "Operation has been canceled, typically by user. (eg. a content download.)" },
    { k_EResultDataCorruption, "Operation canceled because data is ill formed or unrecoverable." },
    { k_EResultDiskFull, "Operation canceled - not enough disk space." },
    { k_EResultRemoteCallFailed, "The remote or IPC call has failed." },
    { k_EResultPasswordUnset, "Password could not be verified as it's unset server side." },
    { k_EResultExternalAccountUnlinked, "External account (PSN, Facebook...) is not linked to a Steam account." },
    { k_EResultPSNTicketInvalid, "PSN ticket was invalid." },
    { k_EResultExternalAccountAlreadyLinked, "External account (PSN, Facebook...) is already linked to some other account, must explicitly request to replace/delete the link first." },
    { k_EResultRemoteFileConflict, "The sync cannot resume due to a conflict between the local and remote files." },
    { k_EResultIllegalPassword, "The requested new password is not allowed." },
    { k_EResultSameAsPreviousValue, "New value is the same as the old one. This is used for secret question and answer." },
    { k_EResultAccountLogonDenied, "Account login denied due to 2nd factor authentication failure." },
    { k_EResultCannotUseOldPassword, "The requested new password is not legal." },
    { k_EResultInvalidLoginAuthCode, "Account login denied due to auth code invalid." },
    { k_EResultAccountLogonDeniedNoMail, "Account login denied due to 2nd factor auth failure - and no mail has been sent." },
    { k_EResultHardwareNotCapableOfIPT, "The users hardware does not support Intel's Identity Protection Technology (IPT)." },
    { k_EResultIPTInitError, "Intel's Identity Protection Technology (IPT) has failed to initialize." },
    { k_EResultParentalControlRestricted, "Operation failed due to parental control restrictions for current user." },
    { k_EResultFacebookQueryError, "Facebook query returned an error." },
    { k_EResultExpiredLoginAuthCode, "Account login denied due to an expired auth code." },
    { k_EResultIPLoginRestrictionFailed, "The login failed due to an IP restriction." },
    { k_EResultAccountLockedDown, "The current users account is currently locked for use. This is likely due to a hijacking and pending ownership verification." },
    { k_EResultAccountLogonDeniedVerifiedEmailRequired, "The logon failed because the accounts email is not verified." },
    { k_EResultNoMatchingURL, "There is no URL matching the provided values." },
    { k_EResultBadResponse, "Bad Response due to a Parse failure, missing field, etc." },
    { k_EResultRequirePasswordReEntry, "The user cannot complete the action until they re-enter their password." },
    { k_EResultValueOutOfRange, "The value entered is outside the acceptable range." },
    { k_EResultUnexpectedError, "Something happened that we didn't expect to ever happen." },
    { k_EResultDisabled, "The requested service has been configured to be unavailable." },
    { k_EResultInvalidCEGSubmission, "The files submitted to the CEG server are not valid." },
    { k_EResultRestrictedDevice, "The device being used is not allowed to perform this action." },
    { k_EResultRegionLocked, "The action could not be complete because it is region restricted." },
    { k_EResultRateLimitExceeded, "Temporary rate limit exceeded, try again later, different from k_EResultLimitExceeded which may be permanent." },
    { k_EResultAccountLoginDeniedNeedTwoFactor, "Need two-factor code to login." },
    { k_EResultItemDeleted, "The thing we're trying to access has been deleted." },
    { k_EResultAccountLoginDeniedThrottle, "Login attempt failed, try to throttle response to possible attacker." },
    { k_EResultTwoFactorCodeMismatch, "Two factor authentication (Steam Guard) code is incorrect." },
    { k_EResultTwoFactorActivationCodeMismatch, "The activation code for two-factor authentication (Steam Guard) didn't match." },
    { k_EResultAccountAssociatedToMultiplePartners, "The current account has been associated with multiple partners." },
    { k_EResultNotModified, "The data has not been modified." },
    { k_EResultNoMobileDevice, "The account does not have a mobile device associated with it." },
    { k_EResultTimeNotSynced, "The time presented is out of range or tolerance." },
    { k_EResultSmsCodeFailed, "SMS code failure - no match, none pending, etc." },
    { k_EResultAccountLimitExceeded, "Too many accounts access this resource." },
    { k_EResultAccountActivityLimitExceeded, "Too many changes to this account." },
    { k_EResultPhoneActivityLimitExceeded, "Too many changes to this phone." },
    { k_EResultRefundToWallet, "Cannot refund to payment method, must use wallet." },
    { k_EResultEmailSendFailure, "Cannot send an email." },
    { k_EResultNotSettled, "Can't perform operation until payment has settled." },
    { k_EResultNeedCaptcha, "The user needs to provide a valid captcha." },
    { k_EResultGSLTDenied, "A game server login token owned by this token's owner has been banned." },
    { k_EResultGSOwnerDenied, "Game server owner is denied for some other reason such as account locked, community ban, vac ban, missing phone, etc." },
    { k_EResultInvalidItemType, "The type of thing we were requested to act on is invalid." },
    { k_EResultIPBanned, "The IP address has been banned from taking this action." },
    { k_EResultGSLTExpired, "This Game Server Login Token (GSLT) has expired from disuse; it can be reset for use." },
    { k_EResultInsufficientFunds, "user doesn't have enough wallet funds to complete the action" },
    { k_EResultTooManyPending, "There are too many of this thing pending already" },
};

// clang-format on

inline std::string_view EResult_getName(const EResult result)
{
    if (result >= EResultMax || result < k_EResultNone) {
        return "Invalid";
    }

    return EResult_names[result];
}

inline std::string_view EResult_getDescription(const EResult result)
{
    if (result >= EResultMax || result < k_EResultNone) {
        return "Invalid";
    }

    return EResult_descriptions[result];
}
