name: release

on:
  push:
    tags:
      - "v*"   # Triggers only when you push a tag starting with "v"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    # Build already outputs the multi-platform artifacts. This is only used just so the workflow runs.
    runs-on: ubuntu-latest
    steps:
      - name: Fetch build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build/release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        # Only release when pushing a tag, just another safe-guard.
        if: github.ref_type == 'tag'
        with:
          files: ./build/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
